kelana.db_host=localhost
kelana.db_user=kelana_test
kelana.db_password=kelana_test
kelana.db_port=${DB_PORT:5432}

spring.flyway.clean-disabled=false
spring.profiles.active=test

admin.username=test
admin.password=test

mqtt.server=tcp://localhost:1883
